eventex/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.core.views',
    url(r'^$', 'homepage', name='homepage'),
    url(r'^palestrantes/(?P<slug>[\w-]+)/$', 'speaker_detail', name='speaker_detail'),
)

eventex/subscriptions/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views',
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'detail', name='detail'),
)

eventex/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('eventex.core.urls', namespace='core')),
    #url(r'^inscricao/(\d+)/$', 'eventex.subscriptions.views.detail', name='detail'),
    # Examples:
    # url(r'^$', 'eventex.views.home', name='home'),
    # url(r'^eventex/', include('eventex.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
)

eventex/core/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Speaker(models.Model):
    name = models.CharField(_('Nome'), max_length=255)
    slug = models.SlugField(_('Slug'))
    url = models.URLField(_('Url'))
    description = models.TextField(_(u'Descrição'), blank=True)

    def __unicode__(self):
        return self.name

class Contact(models.Model):
    KINDS = (
        ('P', _('Telefone')),
        ('F', _('Fax')),
        ('E', _('E-mail')),
    )

    speaker = models.ForeignKey('Speaker', verbose_name=_('palestrante'))
    kind = models.CharField(_('tipo'), max_length=1, choices=KINDS)
    value = models.CharField(_('valor'), max_length=255)

    def __unicode__(self):
        return self.value

eventex/subscriptions/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Subscription(models.Model):
    name = models.CharField(_('nome'), max_length=100)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    email = models.EmailField(_('email'), blank=True)
    phone = models.CharField(_('telefone'), max_length=20, blank=True)
    created_at = models.DateTimeField(_('criado em'), auto_now_add=True)
    paid = models.BooleanField(_('Pago'))

    class Meta:
        ordering = ['created_at']
        verbose_name = _(u'inscrição')
        verbose_name_plural = _(u'inscrições')

    def __unicode__(self):
        return self.name

eventex/subscriptions/forms.py
# coding: utf-8
from django import forms
from eventex.subscriptions.models import Subscription
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.core.validators import EMPTY_VALUES

def CPFValidator(value):
    if not value.isdigit():
        raise ValidationError(_(u'CPF deve conter apenas números'))
    if len(value) != 11:
        raise ValidationError(_(u'CPF deve ter 11 números'))

class PhoneWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (
            forms.TextInput(attrs=attrs),
            forms.TextInput(attrs=attrs))
        super(PhoneWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if not value:
            return [None, None]
        return value.split('-')

class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (forms.IntegerField(),
                  forms.IntegerField())
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''

        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'DDD inválido.'))
        if data_list[1] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'Número inválido.'))
        return '%s-%s' % tuple(data_list)

class SubscriptionForm(forms.ModelForm):
    #name = forms.CharField(label=_('Nome'))
    #cpf = forms.CharField(label=_('CPF'), max_length=11)
    #email = forms.EmailField(label=_('Email'))
    phone = PhoneField(label=_('Telefone'), required=False)
    class Meta:
        model = Subscription
        fields = ['name', 'cpf', 'email', 'phone']

    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)

        self.fields['cpf'].validators.append(CPFValidator)

    def clean_name(self):
        name = self.cleaned_data['name']
        words = map(lambda w: w.capitalize(), name.split())
        capitalized_name = ' '.join(words)
        return capitalized_name

    def clean(self):
        super(SubscriptionForm, self).clean()
        if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
            raise ValidationError(_(u'Informe seu e-mail ou telefone'))

        return self.cleaned_data

eventex/core/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404
from eventex.core.models import Speaker

def homepage(request):
    return render(request, 'core/index.html')

def speaker_detail(request, slug):
    speaker = get_object_or_404(Speaker, slug=slug)
    context = {'speaker': speaker}
    return render(request, 'core/speaker_detail.html', context)

eventex/subscriptions/views.py
# coding: utf-8
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from eventex.subscriptions.forms import SubscriptionForm
from eventex.subscriptions.models import Subscription

def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)
 
def new(request):
    return render(request, 'subscriptions/subscription_form.html', {'form': SubscriptionForm()})

def create(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return render(request, 'subscriptions/subscription_form.html', {'form': form})
    
    obj = form.save()
    return HttpResponseRedirect('/inscricao/%d/' % obj.pk)

def detail(request, pk):
    subscription = get_object_or_404(Subscription, pk=pk)
    return render(request, 'subscriptions/subscription_detail.html', {'subscription': subscription})

eventex/core/templates/core/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>{% block titulo %}EventeX{% endblock %}</title>

    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }

      .footer p {
        float: left;
      }
      .footer a {
        float: right;
      }

    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="/" title="Home">Home</a></li>
        </ul>
        <h3 class="muted"><a href="/" title="Home">EventeX</a></h3>
      </div>

      <hr>
        <div>
        {% block conteudo %}
        {% endblock %}
        </div>
      <hr>

      <div class="footer">
        <p>&copy; WTTD 2013</p>
        <a href="http://www.djangoproject.com/" id="django"><img src="https://djangoproject.com/s/img/badges/djangosite100x25.gif" border="0" alt="A Django site." title="A Django site." /></a>
      </div>

    </div>
  </body>
</html>

eventex/core/templates/core/index.html
{% extends "core/base.html" %}
    {% block conteudo %}
      <div class="jumbotron">
        <h1>Bem-vindo ao EventeX</h1>
        <p class="lead">O evento mais sensacional do ano depois do Dev in Rio! Você não pode perder esta oportunidade!</p>
        <a class="btn btn-large btn-success" href="{% url 'subscriptions:subscribe' %}">Inscreva-se agora</a>
      </div>

      <hr>

      <div class="row-fluid marketing">
        <div class="span6">
          <h4>Dúvidas?</h4>
          <p>Para mais informações e tirar suas dúvidas, entre em contato com eventex@eventex.com.br.</p>

        </div>

        <div class="span6">
          <h4>Patrocinadores</h4>
          <p>Nope</p>
        </div>
      </div>
    {% endblock %}

eventex/core/templates/core/speaker_detail.html
{% extends "core/base.html" %}
{% block conteudo %}
<h3><a href="{{ speaker.url }}">{{ speaker.name }}</a></h3>
<p>{{ speaker.description }}</p>
{% endblock %}

eventex/subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'core/base.html' %}

{% block titulo %}Sucesso{% endblock %}

{% block conteudo %}
    <p>Parabéns {{ subscription.name }},</p>
    <p>sua inscrição foi realizada em {{ subscription.created_at|date:"d/m/Y" }}.</p>
    <p>Em breve, entraremos em contato pelo
    {% if subscription.phone %}
     telefone {{ subscription.phone }}
    {% else %}
     e-mail {{ subscription.email }}
    {% endif %}
    </p>
{% endblock %}

eventex/subscriptions/templates/subscriptions/subscription_form.html
{% extends 'core/base.html' %}

{% block titulo %}Nova Inscrição{% endblock %}

{% block conteudo %}

<h2>Nova Inscrição</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <p>
        <label for="{{ form.name.id_for_label }}">{{ form.name.label  }}</label>
        {{ form.name }}
        {{ form.name.errors }}
    </p>
    <p>
        <label for="{{  form.cpf.id_for_label  }}">{{  form.cpf.label  }}</label>
        {{ form.cpf }}
        {{ form.cpf.errors }}
    </p>
    <p>
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
        {{ form.email }}
        {{ form.email.error }}
    </p>
    <p>
        <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
        {{ form.phone }}
        {{ form.phone.error }}
    </p>
    <input type="submit" value="Enviar!" class="btn btn-success">
</form>

{% endblock %}